QLTapChi/Areas/Admin/Controllers/BaiBaoController.cs
using QLTapChi.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLTapChi.Areas.Admin.Controllers
{
    public class BaiBaoController : Controller
    {
        // GET: Admin/BaiBao
        QLTapChiEntities db = new QLTapChiEntities();
        public ActionResult Index()
        {
            var BaiBao = db.TapChiBaiViets.OrderByDescending(x =>x.IDTapChiBaiViet).ToList();
            return View(BaiBao);
        }
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(TapChiBaiViet model, HttpPostedFileBase File)
        {
            model.TrangThai = 0;
            model.NgayGui = DateTime.Now;
            if (File != null && File.ContentLength > 0)
            {
                string rootFolder = Server.MapPath("/Content/BaiViet/");
                string pathImage = rootFolder + File.FileName;
                File.SaveAs(pathImage);
                //Lưu thuộc tính url
                model.NoiDung = "Content/BaiViet/" + File.FileName;
                db.TapChiBaiViets.Add(model);

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult CapNhatBaiBao(int id)
        {
            var baiBao = db.TapChiBaiViets.FirstOrDefault(s => s.IDTapChiBaiViet == id);
            if (baiBao == null)
            {
                return HttpNotFound();
            }

            return View(baiBao);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CapNhatBaiBao(TapChiBaiViet model, HttpPostedFileBase File)
        {
            var updateModel = db.TapChiBaiViets.Find(model.IDTapChiBaiViet);
            //2.Gán Giá Trị cho đối tượng
            updateModel.TieuDe = model.TieuDe;
            updateModel.TrangThai = model.TrangThai;
            updateModel.LinhVuc = model.LinhVuc;
            updateModel.GhiChu = model.GhiChu;
           
            
            if (File != null && File.ContentLength > 0)
            {
                string rootFolder = Server.MapPath("/Content/BaiViet/");
                string pathImage = rootFolder + File.FileName;
                File.SaveAs(pathImage);
                // Lưu thuộc tính url
                updateModel.NoiDung = "Content/BaiViet/" + File.FileName;

            }

             db.SaveChanges();
                return RedirectToAction("Index");
           
        }
        public ActionResult XoaBaiBao(int id)
        {
            var model = db.TapChiBaiViets.Find(id);
            if (model != null)
            {
                db.TapChiBaiViets.Remove(model);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult DownloadFile(int id)
        {
            // Tìm bài báo theo ID
            var baiBao = db.TapChiBaiViets.FirstOrDefault(b => b.IDTapChiBaiViet == id);

            // Nếu không tìm thấy bài báo, trả về 404
            if (baiBao == null)
            {
                return HttpNotFound();
            }

            // Lấy đường dẫn tới file (trong trường hợp là "NoiDung" là đường dẫn file)
            string filePath = Server.MapPath("~/" + baiBao.NoiDung);

            // Kiểm tra file có tồn tại không
            if (!System.IO.File.Exists(filePath))
            {
                return HttpNotFound();
            }

            // Lấy tên file
            string fileName = Path.GetFileName(filePath);

            // Trả về file dưới dạng download
            return File(filePath, "application/octet-stream", fileName);
        }

        //public ActionResult ChiTietSanPham(int id)
        //{
        //    // Tìm sản phẩm theo ID
        //    var sanPham = db.SanPhams
        //    .Include(s => s.HangSX)         // Lấy đầy đủ thông tin từ HangSX
        //    .Include(s => s.LoaiSanPham)     // Lấy đầy đủ thông tin từ LoaiSanPham
        //    .FirstOrDefault(s => s.IDSanPham == id);
        //    if (sanPham == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    // Lấy thông tin chi tiết sản phẩm từ bảng ThongTinChiTietSP
        //    var thongTinChiTiet = db.ThongTinChiTietSPs.FirstOrDefault(c => c.id_sanpham == id);

        //    // Tạo ViewModel để chuyển thông tin sản phẩm và chi tiết sản phẩm vào View
        //    // ViewModel này đã được thêm tại Folder (Models)
        //    var viewModel = new SanPhamViewModel
        //    {
        //        SanPham = sanPham,
        //        ThongTinChiTiet = thongTinChiTiet,
        //        HangSX = sanPham.HangSX,
        //        LoaiSanPham = sanPham.LoaiSanPham
        //    };

        //    return View(viewModel); // Trả về View hiển thị chi tiết sản phẩm
        //}
    }
}

QLTapChi/Areas/Admin/Views/BaiBao/Add.cshtml
@model QLTapChi.Models.TapChiBaiViet
@using QLTapChi.Models;
@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    QLTapChiEntities db = new QLTapChiEntities();
}

<h2>Add</h2>

@using (Html.BeginForm("Add", "BaiBao", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>TapChiBaiViet</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TieuDe, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TacGia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TacGia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TuKhoa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TuKhoa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TuKhoa, "", new { @class = "text-danger" })
        </div>
    </div>
    <!-- Trường upload file Word -->
    <div class="form-group">
        <label class="control-label col-md-2" style="text-align:left;padding-left:20px;">Tải file</label>
        <div class="col-md-10">
            <input type="file" name="File" />
            @*@Html.EditorFor(model => model.Anh, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Ghi Chú</label>
        <div class="col-md-10">
            @Html.TextAreaFor(x => x.GhiChu, new { @class = "form-control", @id = "txtDetail" })
        </div>
        @*<textarea class="form-control" name="GhiChu" id="txtDetail"></textarea>*@
    </div>

    <div class="form-group">

        <div class="col-md-10">

            <label for="linhVuc" class="form-label">Lĩnh vực</label>
            @{
                var linhvuc = db.LinhVucs.ToList();
            }
            <select class="form-control" name="IDLinhVuc">
                <option value="">Chọn lĩnh vực</option>
                @foreach (var item in linhvuc)
                {
                    <option value="@item.IDLinhVuc" @(Model?.IDLinhVuc == item.IDLinhVuc ? "selected" : "")>@item.TenLinhVuc</option>
                }
            </select>
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section  scripts{
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            if (typeof CKEDITOR !== 'undefined') {
                CKEDITOR.replace('txtDetail', {
                    customConfig: '/Content/ckeditor/config.js',
                    extraAllowedContent: 'span',
                });
            } else {
                console.error("CKEDITOR is not defined.");
            }
        });

        function BrowseServer(field) {
            var finder = new CKFinder();
            finder.selectActionFunction = function (fileUrl) {
                document.getElementById(field).value = fileUrl;
            };
            finder.popup();
        }
        //$(document).ready(function () {
        //    CKEDITOR.replace('txtDetail', {
        //        customConfig: '/Content/ckeditor/config.js',
        //        extraAllowedContent: 'span',
        //    });
        //});
        //function BrowseServer(field) {
        //    var finder = new CKFinder();
        //    finder.selectActionFunction = function (fileUrl) {
        //        document.getElementById(field).value = fileUrl;
        //    };
        //    finder.popup();
        //}
    </script>
}

QLTapChi/Areas/Admin/Views/BaiBao/CapNhatBaiBao.cshtml
@model QLTapChi.Models.TapChiBaiViet
@using QLTapChi.Models;
@{
    ViewBag.Title = "CapNhatBaiBao";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    QLTapChiEntities db = new QLTapChiEntities();
}

<h2>CapNhatBaiBao</h2>

@using (Html.BeginForm("CapNhatBaiBao", "BaiBao", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TapChiBaiViet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDTapChiBaiViet)

        <div class="form-group">
            @Html.LabelFor(model => model.TieuDe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TacGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TacGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Lĩnh vực</label>
            <div class="col-md-10">

                @{
                    var linhvuc = db.LinhVucs.ToList();
                }
                <select class="form-control" name="IDLinhVuc">

                    @foreach (var item in linhvuc)
                    {
                        <option value="@item.IDLinhVuc" )>@item.TenLinhVuc</option>
                    }
                </select>

            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Trạng Thái</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                <select class="form-control" id="PhanBien" name="PhanBien">
                    <option value="1" @(Model.TrangThai == null || Model.TrangThai == 1 ? "selected" : "")>Chưa phản biện</option>
                    <option value="2" @(Model.TrangThai == 2 ? "selected" : "")>Đã phản biện</option>
                </select>
                @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayGui, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGui, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayGui, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="col-md-10">
                    @Html.TextAreaFor(x => x.GhiChu, new { @class = "form-control", @id = "txtDetail" })
                </div>
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section  scripts{
    <script>
       
        $(document).ready(function () {
            CKEDITOR.replace('txtDetail', {
                customConfig: '/Content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });
        function BrowseServer(field) {
            var finder = new CKFinder();
            finder.selectActionFunction = function (fileUrl) {
                document.getElementById(field).value = fileUrl;
            };
            finder.popup();
        }
    </script>
}

QLTapChi/Areas/Admin/Views/BaiBao/Index.cshtml
@model IEnumerable<QLTapChi.Models.TapChiBaiViet>

@{
    ViewBag.Title = "Danh Sách Tạp Chí";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="p-3">
    <h2 class="p-2 text-bg-light w-75">Danh Sách Tạp Chí</h2>

    @if (TempData["Error"] != null)
    {
        <div class="alert alert-danger">
            @TempData["Error"]
        </div>
    }
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success">@TempData["Success"]</div>
    }

    <table class="table">
        <thead>
            <tr>
                <th>Tiêu Đề</th>
                <th>Tác Giả</th>
                <th>Từ Khóa</th>
                <th>Nội Dung</th>
                <th>Trạng Thái</th>
                <th>Ngày Gửi</th>
                <th>Tên Lĩnh Vực</th>
                <th>Thao tác</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.TieuDe)</td>
                    <td>@Html.DisplayFor(modelItem => item.TacGia)</td>
                    <td>@Html.DisplayFor(modelItem => item.TuKhoa)</td>
                    <td>
                        <a href="@Url.Action("DownloadFile", "BaiBao", new { id = item.IDTapChiBaiViet })" class="btn btn-sm btn-outline-dark">Download</a>
                    </td>
                    <td>
                        @{
                            string badgeHtml = "";
                            switch (item.TrangThai)
                            {
                                case 0:
                                    badgeHtml = "<span class='badge bg-warning text-dark'>Chờ TBT phân công</span>";
                                    break;
                                case 1:
                                    badgeHtml = "<span class='badge bg-info text-dark'>Chờ BTV phân công</span>";
                                    break;
                                case 2:
                                    badgeHtml = "<span class='badge bg-primary'>Chờ PB phản hồi</span>";
                                    break;
                            }
                        }
                        @Html.Raw(badgeHtml)
                    </td>
                    <td>@item.NgayGui.ToString("dd/MM/yyyy")</td>
                    <td>@Html.DisplayFor(modelItem => item.LinhVuc.TenLinhVuc)</td>
                    <td>
                        <a href="@Url.Action("XoaBaiBao", "BaiBao", new { id = item.IDTapChiBaiViet })"
                           onclick="return confirm('Bạn có chắc chắn muốn xóa bài báo này không?');">
                            <i class="fas fa-trash"></i>
                        </a>
                        | 
                        <a href="@Url.Action("CapNhatBaiBao", "BaiBao", new { id = item.IDTapChiBaiViet })">
                            <i class="fas fa-edit"></i>
                        </a>
                        | 
                        <a href="@Url.Action("ChiTietBaiBao", "BaiBao", new { id = item.IDTapChiBaiViet })">
                            <i class="fas fa-info-circle"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>